#!/usr/bin/env python3
"""Writes src/game_setup/game_files_table.inc: path, size and SHA-256 of every file of an
extracted Torchlight XBLA package (the one supported version). Facts about the files only; run on a
pristine extraction (nothing added: no import/, no language packs).

Usage: make_table.py EXTRACTED_DIR [OUTPUT]
"""
import hashlib
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
output = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else
                      pathlib.Path(__file__).resolve().parents[2] / 'src/game_setup/game_files_table.inc')
lines = ['// Generated by tools/game_files/make_table.py from Torchlight XBLA 1.0.140.0 (title',
         '// 0x58410A7E): path, size and SHA-256 of each file of the package. Do not edit.']
for path in sorted(p for p in root.rglob('*') if p.is_file()):
    relative = path.relative_to(root).as_posix()
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    lines.append(f'{{"{relative}", {path.stat().st_size}, "{digest}"}},')
output.write_text('\n'.join(lines) + '\n')
print(f'{len(lines) - 2} files -> {output}')
