#include "save_import/schema.h"

#include <stdexcept>

#include "save_import/json.h"

// Generated by CMake from tools/save_convert/character_save.schema.json.
extern const unsigned char kSchemaJsonBytes[];
extern const size_t kSchemaJsonSize;

namespace torchlight::save_import {
namespace {

struct SchemaError : std::runtime_error {
  using std::runtime_error::runtime_error;
};

bool NumberType(std::string_view type, FieldType& out) {
  static const std::pair<std::string_view, FieldType> kTypes[] = {
      {"u8", FieldType::kU8},   {"u16", FieldType::kU16}, {"u32", FieldType::kU32},
      {"u64", FieldType::kU64}, {"f32", FieldType::kF32},
  };
  for (const auto& [name, value] : kTypes) {
    if (name == type) {
      out = value;
      return true;
    }
  }
  return false;
}

const std::string& String(const Json& object, std::string_view key, std::string_view where) {
  const Json* value = object.Find(key);
  if (!value || !value->is_string()) {
    throw SchemaError(std::string(where) + ": missing string '" + std::string(key) + "'");
  }
  return value->string();
}

class Compiler {
 public:
  Compiler(const Json& structs, std::map<std::string, std::unique_ptr<Struct>, std::less<>>& out)
      : out_(out) {
    // Every struct exists before any field points at it (structs refer to each other recursively).
    for (const auto& [name, _] : structs.members()) {
      auto s = std::make_unique<Struct>();
      s->name = name;
      out_[name] = std::move(s);
    }
    for (const auto& [name, definition] : structs.members()) {
      const Json* fields = definition->Find("fields");
      if (!fields || !fields->is_array()) throw SchemaError("struct " + name + ": no fields");
      out_[name]->fields = Fields(*fields, name);
    }
  }

 private:
  std::vector<Field> Fields(const Json& list, const std::string& where) {
    std::vector<Field> fields;
    if (list.is_object()) {
      fields.push_back(One(list, where));
      return fields;
    }
    for (const auto& item : list.items()) fields.push_back(One(*item, where));
    return fields;
  }

  Field One(const Json& json, const std::string& where) {
    if (!json.is_object()) throw SchemaError(where + ": a field is not an object");
    Field field;
    if (const Json* test = json.Find("if")) {
      field.type = FieldType::kCondition;
      if (!test->is_object() || test->members().size() != 1 ||
          !test->members()[0].second->is_integer()) {
        throw SchemaError(where + ": bad condition");
      }
      const auto& [kind, value] = test->members()[0];
      if (kind == "version_ge") field.test = Field::Test::kGreaterOrEqual;
      else if (kind == "version_lt") field.test = Field::Test::kLess;
      else if (kind == "version_eq") field.test = Field::Test::kEqual;
      else throw SchemaError(where + ": unknown condition " + kind);
      field.version = static_cast<uint32_t>(value->integer());
      const Json* then_fields = json.Find("then");
      if (!then_fields) throw SchemaError(where + ": condition without 'then'");
      field.then_fields = Fields(*then_fields, where);
      if (const Json* else_fields = json.Find("else")) field.else_fields = Fields(*else_fields, where);
      return field;
    }
    field.name = String(json, "name", where);
    const std::string path = where + "/" + field.name;
    const std::string& type = String(json, "type", path);
    if (const Json* role = json.Find("role")) field.role = role->string();
    if (const Json* only = json.Find("only_if_set")) field.only_if_set = only->string();
    if (const Json* check = json.Find("check")) {
      if (check->string() != "end_of_element") throw SchemaError(path + ": unknown check");
      field.end_of_element = true;
    }
    if (NumberType(type, field.type)) {
      if (const Json* count = json.Find("count")) field.fixed_count = static_cast<int>(count->integer());
      if (const Json* product = json.Find("count_product")) {
        for (const auto& name : product->items()) field.count_product.push_back(name->string());
      }
    } else if (type == "wstring16" || type == "wstring32") {
      field.type = type == "wstring16" ? FieldType::kWString16 : FieldType::kWString32;
    } else if (type == "struct") {
      field.type = FieldType::kStruct;
      const std::string& name = String(json, "struct", path);
      auto found = out_.find(name);
      if (found == out_.end()) throw SchemaError(path + ": unknown struct " + name);
      field.target = found->second.get();
    } else if (type == "repeat" || type == "list") {
      field.type = type == "repeat" ? FieldType::kRepeat : FieldType::kList;
      if (field.type == FieldType::kRepeat) {
        const Json* times = json.Find("times");
        if (!times || !times->is_integer()) throw SchemaError(path + ": repeat without 'times'");
        field.times = static_cast<int>(times->integer());
      } else if (!NumberType(String(json, "count", path), field.count_type) ||
                 (field.count_type != FieldType::kU16 && field.count_type != FieldType::kU32)) {
        throw SchemaError(path + ": list count must be u16 or u32");
      }
      const Json* of = json.Find("of");
      if (!of) throw SchemaError(path + ": no 'of'");
      if (of->is_array()) {
        field.item_is_element = true;
        field.item_fields = Fields(*of, path);
      } else {
        field.item = std::make_unique<Field>(One(*of, path));
      }
    } else {
      throw SchemaError(path + ": unknown type " + type);
    }
    return field;
  }

  std::map<std::string, std::unique_ptr<Struct>, std::less<>>& out_;
};

}  // namespace

std::unique_ptr<Schema> Schema::FromJson(std::string_view text, std::string& error) {
  auto json = Json::Parse(text, error);
  if (!json) {
    error = "schema JSON: " + error;
    return nullptr;
  }
  auto schema = std::unique_ptr<Schema>(new Schema());
  try {
    const Json* structs = json->Find("structs");
    if (!structs || !structs->is_object()) throw SchemaError("no 'structs'");
    Compiler compiler(*structs, schema->structs_);
    schema->root_ = schema->Find(String(*json, "root", "schema"));
    schema->stash_root_ = schema->Find(String(*json, "stash_root", "schema"));
    if (!schema->root_ || !schema->stash_root_) throw SchemaError("unknown root struct");
  } catch (const SchemaError& e) {
    error = std::string("schema: ") + e.what();
    return nullptr;
  }
  return schema;
}

std::unique_ptr<Schema> Schema::Embedded(std::string& error) {
  return FromJson({reinterpret_cast<const char*>(kSchemaJsonBytes), kSchemaJsonSize}, error);
}

const Struct* Schema::Find(std::string_view name) const {
  auto found = structs_.find(name);
  return found == structs_.end() ? nullptr : found->second.get();
}

}  // namespace torchlight::save_import
