// The save schema (tools/save_convert/character_save.schema.json), compiled from its JSON into
// typed fields. The same file drives the Python tool and this port: the JSON is embedded in the
// executable at build time (schema_data.cpp, generated by CMake). See tools/save_convert/savefile.py
// for the meaning of each construct; this mirrors it one to one.

#pragma once

#include <map>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

namespace torchlight::save_import {

enum class FieldType {
  kU8, kU16, kU32, kU64, kF32,  // numbers (f32 kept as its raw 32 bits)
  kWString16, kWString32,       // UTF-16 text, count of code units first
  kStruct,                      // another struct of the schema
  kRepeat,                      // `times` items
  kList,                        // count (u16 or u32) then that many items
  kCondition,                   // `if` on the file's version: `then` or `else` fields
};

struct Struct;

struct Field {
  FieldType type = FieldType::kU32;
  std::string name;

  // Numbers: a fixed array (`count`), an array sized by the product of sibling fields
  // (`count_product`), or one value.
  int fixed_count = -1;
  std::vector<std::string> count_product;
  std::string role;          // unit_guid, quest_name, version...
  std::string only_if_set;   // sibling GUID that must not be "none" for the reference to count
  bool end_of_element = false;  // holds the absolute offset of the end of its element

  const Struct* target = nullptr;  // kStruct

  int times = 0;                     // kRepeat
  FieldType count_type = FieldType::kU32;  // kList

  // kRepeat / kList items: one field, or an element made of several fields.
  std::unique_ptr<Field> item;
  std::vector<Field> item_fields;
  bool item_is_element = false;

  // kCondition
  enum class Test { kGreaterOrEqual, kLess, kEqual } test = Test::kEqual;
  uint32_t version = 0;
  std::vector<Field> then_fields, else_fields;
};

struct Struct {
  std::string name;
  std::vector<Field> fields;
};

class Schema {
 public:
  // The schema embedded in the executable. Null, with `error` set, if it does not compile (a build
  // problem, caught by the tests).
  static std::unique_ptr<Schema> Embedded(std::string& error);
  static std::unique_ptr<Schema> FromJson(std::string_view json, std::string& error);

  const Struct* root() const { return root_; }              // a character save
  const Struct* stash_root() const { return stash_root_; }  // a shared stash
  const Struct* Find(std::string_view name) const;

 private:
  std::map<std::string, std::unique_ptr<Struct>, std::less<>> structs_;
  const Struct* root_ = nullptr;
  const Struct* stash_root_ = nullptr;
};

}  // namespace torchlight::save_import
