# Writes build_info.h (TORCHLIGHT_BUILD_COMMIT: the source tree's commit, "-dirty" with local
# changes, "unknown" without git) when it changes. Run on every build: cmake -DSOURCE_DIR=...
# -DOUTPUT=... -P build_info.cmake.
execute_process(
    COMMAND git -C "${SOURCE_DIR}" describe --always --dirty --abbrev=12
    OUTPUT_VARIABLE _commit
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _result)
if(NOT _result EQUAL 0 OR _commit STREQUAL "")
    set(_commit "unknown")
endif()
set(_content "// Generated by cmake/build_info.cmake.\n#pragma once\n#define TORCHLIGHT_BUILD_COMMIT \"${_commit}\"\n")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
    if(_old STREQUAL _content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${_content}")
