# The tests' user folders (CMakeLists.txt, test_home fixture). MODE=setup: an empty TEST_HOME, and a
# list of what the real user folders hold (SNAPSHOT). MODE=check: TEST_HOME removed, and a failure
# if the real user folders gained anything since the setup. Run with the real environment (these
# two tests do not get TORCHLIGHT_TEST_USER_FOLDERS). The real folders: on Linux the XDG base
# directories (platform/user_folders_linux.cpp); on Windows %APPDATA% and %LOCALAPPDATA% (whichever
# of them the Windows platform file uses). logs/ is left out, since a game running meanwhile writes
# there.
cmake_minimum_required(VERSION 3.25)

function(user_folder_bases out)
    set(bases)
    if(CMAKE_HOST_WIN32)
        set(${out} "$ENV{APPDATA};$ENV{LOCALAPPDATA}" PARENT_SCOPE)
        return()
    endif()
    foreach(pair "XDG_CONFIG_HOME|.config" "XDG_STATE_HOME|.local/state" "XDG_CACHE_HOME|.cache"
                 "XDG_DATA_HOME|.local/share")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 variable)
        list(GET pair 1 fallback)
        if(DEFINED ENV{${variable}} AND NOT "$ENV{${variable}}" STREQUAL "")
            list(APPEND bases "$ENV{${variable}}")
        else()
            list(APPEND bases "$ENV{HOME}/${fallback}")
        endif()
    endforeach()
    set(${out} "${bases}" PARENT_SCOPE)
endfunction()

function(snapshot out)
    user_folder_bases(bases)
    set(entries)
    foreach(base IN LISTS bases)
        set(folder "${base}/TorchlightRecomp")
        if(EXISTS "${folder}")
            list(APPEND entries "${folder}/")
            file(GLOB_RECURSE files LIST_DIRECTORIES true RELATIVE "${folder}" "${folder}/*")
            foreach(file IN LISTS files)
                if(NOT file MATCHES "^logs(/|$)")
                    list(APPEND entries "${folder}/${file}")
                endif()
            endforeach()
        endif()
    endforeach()
    list(SORT entries)
    set(${out} "${entries}" PARENT_SCOPE)
endfunction()

if(MODE STREQUAL "setup")
    file(REMOVE_RECURSE "${TEST_HOME}")
    file(MAKE_DIRECTORY "${TEST_HOME}")
    snapshot(entries)
    string(REPLACE ";" "\n" text "${entries}")
    file(WRITE "${SNAPSHOT}" "${text}")
elseif(MODE STREQUAL "check")
    file(REMOVE_RECURSE "${TEST_HOME}")
    file(STRINGS "${SNAPSHOT}" before)
    snapshot(after)
    set(new)
    foreach(entry IN LISTS after)
        if(NOT entry IN_LIST before)
            list(APPEND new "${entry}")
        endif()
    endforeach()
    if(new)
        string(REPLACE ";" "\n  " new "${new}")
        message(FATAL_ERROR "the test suite wrote to the user's folders:\n  ${new}")
    endif()
else()
    message(FATAL_ERROR "MODE must be setup or check")
endif()
